#!/bin/bash
#
# VideoKit-KDE - A set of video utilities for KDE, extending Dolphin.
#       - videokit-queue
#
# Author:  Tom Brown (https://github.com/TomB16)
# License: MIT License
# Contact: tom@CarlsonSpeed.com
#
# Copyright (c) 2025 Tom Brown
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


ENTRY="${@:3}"

echo "queue"
echo $1
echo $2
echo $ENTRY
echo "end queue"



case "$1" in
	push)
		echo "$ENTRY" >> $2
		;;
	second)
		if [[ -s "$2" ]]; then
			awk -v newline="$ENTRY" 'NR==1 { print; print newline; next } 1' "$2" > "${2}.tmp"
			mv "${2}.tmp" "$2"
		else
			echo "$ENTRY" > $2
		fi
		;;
	pull)
		if [ -f $2 ] ; then
			head -n 1 $2
			sed -i '1d' $2
		fi
		;;
	look)
		if [ -f $2 ] ; then
			head -n 1 $2
		fi
		;;
	queue)
		if [ -f $2 ] ; then
			less $2
		fi
		;;
esac
