#!/bin/bash

#
# This file is part of videokit-kde.
# Copyright (C) 2025 Tom Brown
#
# videokit-kde is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# videokit-kde is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#


# masthead

source bashdev-app

APP_NAME=$(basename "$0")
APP_VERSION=0.3.0
APP_AUTHOR="Tom Brown"
APP_YEAR="2025"
APP_LICENSE="GNUv3"
APP_DESC="Assign the filename to the meta data title"

app::masthead "$APP_NAME" "$APP_VERSION" "$APP_AUTHOR" "$APP_YEAR" "$APP_LICENSE" "$APP_DESC"


# transcode queue params

source videokit-lib

videokit::configLoad


if [[ "$FILE2TITLE_DEBUG" == "true" ]]; then

        echo "debug:  $FILE2TITLE_DEBUG"
        echo "debug:  Lock file =" $FILE2TITLE_LOCK
        echo "debug:  Tolerance =" $FILE2TITLE_TOLERANCE

fi



# check for file exists

INPUT_FILE="$1"
if [ -z "$INPUT_FILE" ]; then

	echo
    echo "error: no file specified."

else

	# spinlock to serialize multiple execution

	app::processLockSpin $(basename "$0") 202


	# parse the filename

	FILENAME="${INPUT_FILE%.*}"
	EXTENSION="${INPUT_FILE##*.}"
	TARGET_FILE=$FILENAME"_file2title_."$EXTENSION
	TITLE="${FILENAME##*/}"


	# strip the forced and default sub flags

	echo "info:  updating file"
	CMD="nice -n 19 ffmpeg -y -i \"$INPUT_FILE\" -metadata title=\"$TITLE\" -codec copy \"$TARGET_FILE\" >/dev/null 2>&1"
	systemd-inhibit --why="Set metadata title" bash -c "$CMD"


	# action on result

	if [ $? -eq 0 ]; then

		INPUT_SIZE=$( stat -c %s "$INPUT_FILE")
		TARGET_SIZE=$(stat -c %s "$TARGET_FILE")

		DIFF=$(( TARGET_SIZE >= INPUT_SIZE ? TARGET_SIZE - INPUT_SIZE : INPUT_SIZE - TARGET_SIZE ))

		[[ "$DIFF" -le "$FILE2TITLE_TOLERANCE" ]] && mv "$TARGET_FILE" "$INPUT_FILE" || echo "error: difference $DIFF exceeds tolerance $TOLERANCE."

	else
		echo "error: unable to change title"
	fi

fi



# clean up

app::processUnlock
