#!/bin/bash

#
# This file is part of videokit-kde.
# Copyright (C) 2025 Tom Brown
#
# videokit-kde is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# videokit-kde is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#


# masthead

source bashdev-app

APP_NAME=$(basename "$0")
APP_VERSION=0.3.0
APP_AUTHOR="Tom Brown"
APP_YEAR="2025"
APP_LICENSE="GPLv3"
APP_DESC="VideoKit-KDE CLI utility"

app::masthead "$APP_NAME" "$APP_VERSION" "$APP_AUTHOR" "$APP_YEAR" "$APP_LICENSE" "$APP_DESC"


# needed for config information

source bashdev-gpu
source bashdev-video
source bashdev-system
source videokit-lib

videokit::configLoad


# parameter handling

source bashdev-param

param::add -n "preflight"       -d "preflight checks"                                           -r false -t flag    -s p    -l preflight
param::add -n "version"         -d "report version"                                             -r false -t flag    -s v    -l version
param::add -n "reset"           -d "reset process locks"                                        -r false -t flag    -s r    -l reset
param::add -n "anon"            -d "anonymize transcode log"                                    -r false -t flag    -s a    -l anon
param::add -n "queue"           -d "add video to transcode queue"                               -r false -t string  -s q    -l queue
param::add -n "second"          -d "add --queue video to transcode queue in second position"    -r false -t flag    -s s    -l second
param::add -n "log-rotate"      -d "rotate the trancode log [monthly|weekly|daily]"             -r false -t string          -l log-rotate
param::add -n "log-unrotate"    -d "extract archived log file (provide archive filename)"       -r false -t string  -s u    -l log-unrotate
param::parse "$@"


# actions

[[ $( param::get preflight ) == "true" ]] && videokit::preflight
[[ $( param::get version   ) == "true" ]] && echo "videokit-util version $APP_VERSION"
[[ $( param::get reset     ) == "true" ]] && videokit::resetLocks
[[ $( param::get anon      ) == "true" ]] && videokit::logAnonymize
[[ -n "$( param::get log-rotate )"     ]] && videokit::logRotate "$( param::get log-rotate )"
[[ -n "$( param::get log-unrotate )"   ]] && videokit::logUnrotate "$( param::get log-unrotate )"

if [[ -n $( param::get queue ) ]]; then

    [[ $( param::get second ) == "true" ]] && COMMAND="second" || COMMAND="push"
    videokit::transcodeQueue "$COMMAND" "$( param::get queue )"

fi


