#!/bin/bash
#
# VideoKit-KDE - Provide url for videokit config file.
#       - videokit-config
#
# Author:  Tom Brown (https://github.com/TomB16)
# Contact: tom@CarlsonSpeed.com
# License: MIT License
#
# Copyright (c) 2025 Tom Brown
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.




# configure 

GLOBAL="/usr/share/videokit/videokit.conf"
LOCAL="~/.config/videokit.conf"
LOCAL="${LOCAL//\~/$HOME}"


if [ -f $LOCAL ]; then

	crudini --get $LOCAL $1 $2

else

	# create the user config

	if [ -f $GLOBAL ]; then	cp $GLOBAL $LOCAL
	else		   echo Error: Global config not found;		exit 1;		fi

fi


